language: scala

scala:
 - 2.11.7

jdk:
 - oraclejdk8

env:
 - PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH

#cache:
#  directories:
#    - $HOME/.sbt

notifications:
  email:
    recipients:
      - s.c.c.blom@utwente.nl
    on_success: change
    on_failure: always

# mono is not needed for silicon.
#before_script:
# - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
# - echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/3.12.0 main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
# - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
# - sudo apt-get update
# - sudo apt-get install mono-devel
 
addons:
  apt:
    packages:
      - tcl
      - texlive
      - texlive-latex-recommended
      - texlive-latex-extra

script:
# compile the tool set
 - ant compile
# test the back ends (skipped)
# - vct --test=""
# test one example in a way that show all error messages
 - vct --silicon $TRAVIS_BUILD_DIR/examples/manual/fibonacci.pvl
# test the remaining examples while hiding messages
 - vct --tool=silicon --exclude-suite=slow,medium,problem-fail,skip-travis --test=$TRAVIS_BUILD_DIR/examples

#deploy:
#  provider: releases
#  api_key:
#    secure: MFGqeFi8E9eLtcy+5wQ/+xgSKyg3QY2Jm0wRBk6GWyIh3WUdjhI0Fqe3rII/r+AyB2tC3tA8zNzNRar1wOYgVr8zLQwwsfq+K/PfeOPitkKiPmUICeZXEXpTgOhkg53vynN+ZXwV4UcEKR64Z7LMK0mWqpCf3jzv8S9fu0/zV/cwo86LNbHPTRJtVxst25YUVL9X9U3lV7Q+KvRgephjuIG2gz/Ce63uVxVGiTMFETzeL0FM8hdSQUCcRKIFysDxhOh+oofPLkGQOQsET4atNYsqmEXOMnZjU07muqXTrsybz/PhTW2Ioi3AdCR/tfNnoOhBiON6hWyR66db8DKNfiyLmFvyEFsOLm5nNhucU4wvRslRyMfayn+D4nRc/I0I4ozifl0WXfqBbtAqFtUUV1cuWZfIDH9OJF5YfB2mbUs9FYo5CpopjNnGV8rlkzzGm15EWQhMTeq1qpxl+E2NsY0UZ3DoxLRzLEvoykpN9VatiYkrpX6jG9g2u1GZ6E/fDw5NwouUI/tLeaFhvHydMx7GVewKRNWuLC0hct92tKWtjV9tLCVzOoHGuDmWZVRLH6Zn5XJvCfhBZvu7RcM9S5UdJbdW5PYf8qYgTqteIoXYKQUofOGUCsbsBncLuiRT9I1pXMYolAcd06KfTdmhk6QHYCAN1JP6Rgz//r3osSc=
#  file: 'dist/vercors-$TRAVIS_TAG.zip'
#  on:
#    repo: utwente-fmt/vercors
#    tags: true

deploy:
  provider: releases
  api_key:
    secure: MFGqeFi8E9eLtcy+5wQ/+xgSKyg3QY2Jm0wRBk6GWyIh3WUdjhI0Fqe3rII/r+AyB2tC3tA8zNzNRar1wOYgVr8zLQwwsfq+K/PfeOPitkKiPmUICeZXEXpTgOhkg53vynN+ZXwV4UcEKR64Z7LMK0mWqpCf3jzv8S9fu0/zV/cwo86LNbHPTRJtVxst25YUVL9X9U3lV7Q+KvRgephjuIG2gz/Ce63uVxVGiTMFETzeL0FM8hdSQUCcRKIFysDxhOh+oofPLkGQOQsET4atNYsqmEXOMnZjU07muqXTrsybz/PhTW2Ioi3AdCR/tfNnoOhBiON6hWyR66db8DKNfiyLmFvyEFsOLm5nNhucU4wvRslRyMfayn+D4nRc/I0I4ozifl0WXfqBbtAqFtUUV1cuWZfIDH9OJF5YfB2mbUs9FYo5CpopjNnGV8rlkzzGm15EWQhMTeq1qpxl+E2NsY0UZ3DoxLRzLEvoykpN9VatiYkrpX6jG9g2u1GZ6E/fDw5NwouUI/tLeaFhvHydMx7GVewKRNWuLC0hct92tKWtjV9tLCVzOoHGuDmWZVRLH6Zn5XJvCfhBZvu7RcM9S5UdJbdW5PYf8qYgTqteIoXYKQUofOGUCsbsBncLuiRT9I1pXMYolAcd06KfTdmhk6QHYCAN1JP6Rgz//r3osSc=
  file: 'src/tex/manual.pdf'
  on:
    repo: utwente-fmt/vercors
    tags: true  



