(set-option :produce-models true)
(set-option :print-success false)
(set-logic QF_UF)
(declare-fun p () Bool)
(declare-fun q () Bool)
(assert (and p q))
(check-sat)
(get-value (p))
(get-value (q))
(exit)

