# -*- tab-width:4 ; indent-tabs-mode:t -*-

def:
	@echo "please use:"
	@echo "  make manual      to compile the user manual"

manual:
	TEXINPUTS=$(TEXINPUTS):../../examples// pdflatex manual
#	bibtex manual
	TEXINPUTS=$(TEXINPUTS):../../examples// pdflatex manual

