# -*- tab-width:4 ; indent-tabs-mode:t -*-

def:
	@echo "please use:"
	@echo "  make plans      to compile the description of parallel PVL"

manual:
	TEXINPUTS=$(TEXINPUTS):../../examples// pdflatex manual
#	bibtex manual
	TEXINPUTS=$(TEXINPUTS):../../examples// pdflatex manual

