<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pvl</string>
	</array>
	<key>name</key>
	<string>Vercors PVL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#specs</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.pvl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.block.singleline.pvl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([A-Z][a-zA-Z0-9_]*)\b</string>
					<key>name</key>
					<string>variable.language.typename.pvl</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|null|this)\b</string>
					<key>name</key>
					<string>constant.language.bool.pvl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([0-9]+)\b</string>
					<key>name</key>
					<string>constant.numeric.pvl</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.bold</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(class|kernel|global|local|static|thread_local|inline|pure|with|then|in|id|new|unfolding|return|lock|unlock|wait|notify|fork|join|if|else|barrier|par|and|vec|while|goto|void)\b</string>
					<key>name</key>
					<string>entity.name.type.pvl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(int|boolean|option|process|zfrac|frac|set|seq|bag)\b</string>
					<key>name</key>
					<string>keyword.operator.types.pvl</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&amp;&amp;|**</string>
					<key>name</key>
					<string>keyword.operator.pvl</string>
				</dict>
			</array>
		</dict>
		<key>scopedspecs</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>support.class.scoped.spec.pvl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#speckeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scopedspecs</string>
				</dict>
			</array>
		</dict>
		<key>speckeywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(int|boolean|option|process|zfrac|frac|set|seq|bag|modifies|accessible|requires|ensures|given|yields|invariant|context|loop_invariant|create|qed|apply|use|create|destroy|split|merge|choose|fold|unfold|open|close|assert|assume|inhale|exhale|label|refute|witness|ghost|send|recv|transfer|csl_subject|spec_ignore|null|exists|Perm|HPerm|empty|write|false|true|Future|AbstractState|to|from|action|atomic|PointsTo|Value)\b</string>
					<key>name</key>
					<string>markup.bold.scopedspec.pvl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\result|\\exists|\\old|\\forall</string>
					<key>name</key>
					<string>markup.bold.scopedspec.special.pvl</string>
				</dict>
			</array>
		</dict>
		<key>specs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(resource|modifies|accessible|requires|ensures|given|yields|invariant|context|loop_invariant|create|qed|apply|use|create|destroy|split|merge|choose|fold|unfold|open|close|assert|assume|inhale|exhale|label|refute|witness|ghost|send|recv|transfer|csl_subject|spec_ignore)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.bold</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>name</key>
					<string>support.class.spec.pvl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#scopedspecs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#speckeywords</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(action[ ]*\(|atomic[ ]*\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.bold</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>support.class.spec.parenthesis.pvl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#scopedspecs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#speckeywords</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pvl</string>
	<key>uuid</key>
	<string>C65E03EA-0975-40F2-90CF-FD1BDF944050</string>
</dict>
</plist>
